name: Send Chime Reminder Test

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 schedule pytz
    
    - name: Run reminder script
      env:
        CHIME_WEBHOOK_URL: ${{ secrets.CHIME_WEBHOOK_URL }}
        QUIP_API_TOKEN: ${{ secrets.QUIP_API_TOKEN }}
        QUIP_DOC_ID: ${{ secrets.QUIP_DOC_ID }}
      run: |
        python chime_reminder_1.py
