on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz
    
    - name: Run reminder script
      env:
        CHIME_WEBHOOK_URL_1: ${{ secrets.CHIME_WEBHOOK_URL_1 }}
        QUIP_API_TOKEN: ${{ secrets.QUIP_API_TOKEN }}
        QUIP_DOC_ID_1: ${{ secrets.QUIP_DOC_ID_1 }}
        FORCE_SEND: 'false'  # Set this to 'false' for normal operation
      run: |
        python chime_reminder_1.py
