name: Send Reminders

on:
  schedule:
    - cron: '0 9 * * 1-5'  # Runs at 9:00 AM UTC Monday-Friday
  workflow_dispatch:  # Allows manual triggering

jobs:
  send_reminders:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz
    
    - name: Run script
      env:
        QUIP_API_TOKEN: Bearer ${{ secrets.QUIP_API_TOKEN }}  # Added 'Bearer ' prefix
        CHIME_WEBHOOK_URL_1: ${{ secrets.CHIME_WEBHOOK_URL_1 }}
        QUIP_DOCUMENT_ID_1: ${{ secrets.QUIP_DOCUMENT_ID_1 }}
      run: |
        echo "Checking environment variables:"
        echo "QUIP_API_TOKEN is set: ${{ secrets.QUIP_API_TOKEN != '' }}"
        echo "CHIME_WEBHOOK_URL_1 is set: ${{ secrets.CHIME_WEBHOOK_URL_1 != '' }}"
        echo "QUIP_DOCUMENT_ID_1 is set: ${{ secrets.QUIP_DOCUMENT_ID_1 != '' }}"
        python chime_reminder_1.py


