name: Send Chime Reminder

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  send_reminder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run reminder script
      env:
        CHIME_WEBHOOK_URL: ${{ secrets.CHIME_WEBHOOK_URL }}
        QUIP_API_TOKEN: ${{ secrets.QUIP_API_TOKEN }}
        QUIP_DOC_ID: ${{ secrets.QUIP_DOC_ID }}
      run: python reminder_script.py
