name: Send Chime Reminder

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
 workflow_dispatch:  # Allows manual trigger with inputs
    inputs:
      force_send:
        description: 'Force send message (true/false)'
        required: true
        default: 'true'

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pytz
    
    - name: Run reminder script
      env:
        CHIME_WEBHOOK_URL: ${{ secrets.CHIME_WEBHOOK_URL }}
        QUIP_API_TOKEN: ${{ secrets.QUIP_API_TOKEN }}
        QUIP_DOC_ID: ${{ secrets.QUIP_DOC_ID }}
        FORCE_SEND: ${{ github.event.inputs.force_send || 'false' }}
      run: |
        python chime_reminder.py
